CREATE TABLE SECURITY (
	USERNAME VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(50) NOT NULL;
);

CREATE TABLE ULTIMI_LAVORI (
	ID NUMBER(100) NOT NULL PRIMARY KEY,
	TITLE VARCHAR2(100) NOT NULL,
	IMAGE BLOB NOT NULL;
);

CREATE TABLE OFFERTE(
	ID NUMBER(100) NOT NULL PRIMARY KEY,
	TITLE VARCHAR2(100) NOT NULL,
	IMAGE BLOB NOT NULL,
	DESCRIPTION VARCHAR2(200) NOT NULL,
	PRICE VARCHAR2(10) NOT NULL;
);
